name: API-Build

on:
  push:
    paths: 
      - 'api/**'
      - '.github/workflows/api-build.yml'

  workflow_dispatch:

jobs:
  build:
    name: build-dotnet-api
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build
        working-directory: ./api